version: '3.4'
services:
  notepad-backend:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/
      - /usr/src/app/mongodb/
      - /usr/src/app/redis/
    env_file:
      - '.env'
    ports:
      - 3000:3000
    depends_on:
      - redis
    links:
      - redis
    command: npm run start
    networks:
      - application
  redis:
    image: 'bitnami/redis:latest'
    restart: always
    env_file:
      - '.env'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    networks:
      - application
    volumes:
      - ./redis:/bitnami/redis/data
networks:
  application:
    driver: bridge
